### ISSUE TITLE
Wrong resistance value between RW and RL

### ISSUE THREAD

**Issue by OscilloV** [adafruit/Adafruit_CircuitPython_DS3502#8]
I've used the exemple code, and by measuring the voltage between RW and RL it shows the correct voltage.
But then I've measured the resistance between RW and RL and it's not what I would expect. I'm controlling it with the Adafruit FT232H.

**First measure**
VCC = FT232H 3.3V
V+ = FT232H 5V
RH : not connected to any potential
RL : not connected to any potential
Resistance between RH and RL : always 10k, so it's correct

Resistance between RW and RL when wiper 127 : variable 17k - 15k
Resistance between RW and RL when wiper 0 : variable 8k - 4k

**Second measure**
VCC = FT232H  3.3V
V+ = FT232H  5V
RH : not connected to any potential
RL : FT232H  GND
Resistance between RH and RL : always 10k, so it's correct

Resistance between RW and RL when wiper 127 : stable 12.76k
Resistance between RW and RL when wiper 0 : stable 2.8k

**Third measure**
VCC = FT232H  3.3V
V+ = FT232H  5V
RH : not connected to any potential
RL : External alimentation GND
RW : External alimentation 3V
External alimentation **ON**
Resistance between RH and RL when wiper 127 :  not measurable
Resistance between RH and RL when wiper 0 : 10k

Resistance between RW and RL when wiper 127 : not measurable
Resistance between RW and RL when wiper 0 : not measurable

**Fourth measure**
VCC = FT232H  3.3V
V+ = FT232H  5V
RH : not connected to any potential
RL : External alimentation GND
RW : External alimentation 3V
External alimentation **OFF**
Resistance between RH and RL when wiper 127 : 2.8k
Resistance between RH and RL when wiper 0 : 10k

Resistance between RW and RL when wiper 127 : 754ohm
Resistance between RW and RL when wiper 0 : 623ohm

In the third and fourth case is probably the external alimentation influencing the measure, so it would be better with an OPAMP for high impedance.

For the rest I have no idea why is behaving like this.

Thanks

**Comment by jposada202020** [comment]
I tested this with a 
```python3
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
```
using 
`ds3502_simpletest.py `


And in an Ubuntu 20.04 with the FT 232H Rev C using Blinka using
`ds3502_blinka_simpletest.py`

In both cases I got the Voltages as expected. To be clear, I do not understand the `magic` inside the device to manipulate the resistance to get the correct voltage value. But what would be the problem with the library? we are getting what we expect, I am missing something?

**Comment by OscilloV** [comment]
My problem is that for an application I need to know the exact resistance, so that I can calculate the current with a known voltage as an input.
With the example code, I obtain the correct voltage division, but when I mesure the resistance is not the correct value.
<img width="478" alt="ds3502" src="https://user-images.githubusercontent.com/83290464/117575775-93488400-b0e3-11eb-834f-2b885976009c.PNG">

As it show in the datasheet, the resistance is selected with the activation of a CMOS, the resistance value is obtained. In theory if max resistance is 10kOhm, and a selection of 128 states, every step is 78.125Ohm. When the wiper is at 127 the resistance must be 10kOhm, and when the wiper is at 0 the resistance must be 0Ohm.

My doubt is if in addition to the resistances, I'm measuring also the inactive CMOS Rds resistance.

**Comment by jposada202020** [comment]
Thank you for the information, it is more clear know, however I do not have the answer, maybe someone in the Adafruit discord channel or in the Adafruit Forums could answer this, for sure you will have better visibility there. As we use Github for libraries development.

**Comment by OscilloV** [comment]
@jposada202020  Thank you for the informations
